### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by fullv2** [MogiePete/zabbix-galera-template#2]
Hello, thanks for this template, how can I add credentials for connection with galera cluster?
I get "ERROR 1045 (28000): Access denied for user 'zabbix'@'localhost' (using password: NO)"
Is there any other way except change my.cnf file , maybe with Macro or odbc.ini ?

thanks!

**Comment by MogiePete** [comment]
You need to place them in your /etc/my.cnf file. Remember this template is for Linux.

For example:

[client]
user=zabbixmon
passwd=zabbixmon

Since I use the same account to monitor multiple things I use the following:

CREATE USER 'zabbix'@'localhost';
GRANT USAGE ON \*.\* TO 'zabbixmon'@'localhost';
