### ISSUE TITLE
The 'INFORMATION_SCHEMA.GLOBAL_STATUS' feature is disabled; see the documentation for 'show_compatibility_56'

### ISSUE THREAD

**Issue by ignaqui** [MogiePete/zabbix-galera-template#3]
Hi,

I have Percona 5.7 mysql. When I tried to enable the variable, here is the messages I received:

` "select VARIABLE_VALUE from information_schema.GLOBAL_STATUS where VARIABLE_NAME = 'wsrep_cluster_size';" | HOME=/var/lib/zabbix mysql -N
ERROR 3167 (HY000) at line 1: The 'INFORMATION_SCHEMA.GLOBAL_STATUS' feature is disabled; see the documentation for 'show_compatibility_56'`

So I had to add these parameters to galera config file:
`show_compatibility_56 = ON
performance_schema`

Is this the best approach though?

**Comment by MogiePete** [comment]
It is a requirement when using MySQL 5.7 due to the way Oracle is migrating from information_schema to performance_schema.

We utilize MariaDB 10.1 and 10.2 thus we do not encounter this issue as it a MySQL variable for indicating status of certain compatibility traits between MySQL 5.6 and MySQL 5.7.

https://mariadb.com/kb/en/library/system-variable-differences-between-mariadb-102-and-mysql-57/

**Comment by anton-kyrylenko** [comment]
I use the syntax  UserParameter=galera.cluster_conf_id[*],echo "SHOW GLOBAL STATUS LIKE 'wsrep_cluster_conf_id';" | HOME=/var/run/zabbix mysql  -N  without show_compatibility_56 option

**Comment by anton-kyrylenko** [comment]
I use syntax like UserParameter=galera.wsrep_repl_data_bytes[*],echo "SHOW GLOBAL STATUS LIKE 'wsrep_repl_data_bytes';" |HOME=~zabbix mysql -ss | awk '{print $$2}' instead show_compatibility_56 option
